name: Build and Publish

on:
  push:

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    steps:
      - id: tag_build_number
        run: echo "tag=$(echo ${{github.ref_name}} | tr -cs 'a-zA-Z0-9' '-')$(date +'%Y%m%d%H%M%S')-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - id: tag_snapshot
        run: echo "tag=$(echo ${{github.ref_name}} | tr -cs 'a-zA-Z0-9' '-')snapshot" >> $GITHUB_OUTPUT
      - id: repo
        run: echo "repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    outputs:
      tag_build_number: ${{ steps.tag_build_number.outputs.tag }}
      tag_snapshot: ${{ steps.tag_snapshot.outputs.tag }}
      repo: ${{ steps.repo.outputs.repo }}
  build:
    runs-on: ubuntu-latest
    needs: prepare-variables
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Build
        run: |
          cd maas-agent-service
          CGO_ENABLED=0 go build

      - name: Test with coverage
        run: |
          cd maas-agent-service
          go test -v ./... -coverprofile coverage.out

      - name: Upload coverage report to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dproject.settings=sonar-project.properties
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.organization=vladislav-larkin-test-organization
            -Dsonar.go.coverage.reportPaths=coverage.out
        working-directory: maas-agent-service

